"""cria tabelas devices, device_credentials e heartbeats

Revision ID: 7c0f6a09eba7
Revises: 
Create Date: 2026-09-26 09:40:05.194611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c0f6a09eba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('asset_number', sa.String(length=50), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('reported_ip', sa.String(length=45), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_asset_number'), 'devices', ['asset_number'], unique=True)
    op.create_table('device_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='device_credential_status'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_credentials_device_id'), 'device_credentials', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_credentials_key_id'), 'device_credentials', ['key_id'], unique=True)
    op.create_table('heartbeats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('reported_ip', sa.String(length=45), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('device_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heartbeats_device_id'), 'heartbeats', ['device_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heartbeats_device_id'), table_name='heartbeats')
    op.drop_table('heartbeats')
    op.drop_index(op.f('ix_device_credentials_key_id'), table_name='device_credentials')
    op.drop_index(op.f('ix_device_credentials_device_id'), table_name='device_credentials')
    op.drop_table('device_credentials')
    op.drop_index(op.f('ix_devices_asset_number'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
    # NOTA MANUAL (não gerado pelo autogenerate): DROP TABLE não apaga o tipo
    # ENUM nativo do Postgres associado à coluna — sem esta linha, um upgrade
    # posterior falha com "type device_credential_status already exists".
    sa.Enum(name="device_credential_status").drop(op.get_bind(), checkfirst=True)
